### ISSUE TITLE
"Update" Activity not created when post is updated

### ISSUE THREAD

**Issue by nigini** [microblog-pub/microblog.pub#18]
Our current `update_post` procedure does not follow the [W3C ActivityPub specification](https://www.w3.org/TR/activitypub/#update-activity-inbox): 

> For server to server interactions, an Update activity means that the receiving server SHOULD update its copy of the object of the same id to the copy supplied in the Update activity.

My current understanding is that such an Activity should be created and posted to the outbox, which I cannot verify but manually looking into the database after the update presented [in this issue](https://github.com/microblog-pub/microblog.pub/issues/11#issuecomment-2333207840).

**Comment by 1dom** [comment]
I haven't tried to test it, but stepping through the code, it looks like it probably should be sending the update activity already.  The update stuff starts by calling this existing boxes.py/send_update function, the bit in that function which triggers the send is new_outgoing_activity: https://github.com/microblog-pub/microblog.pub/blob/v2.1-dev/app/boxes.py#L892

That function basically adds a message to the outgoing messages queue: https://github.com/microblog-pub/microblog.pub/blob/v2.1-dev/app/outgoing_activities.py#L100 so that it can then be picked up by the process_outgoing_activity thread.

That process_activity_thread gets the object and then figures out if it's a Create or Update activity via wrap_object_if_needed, called here: https://github.com/microblog-pub/microblog.pub/blob/v2.1-dev/app/outgoing_activities.py#L220

That creates the Update activity by wrapping the object and adding `type: Update` here: https://github.com/microblog-pub/microblog.pub/blob/v2.1-dev/app/activitypub.py#L336

Did you notice any errors from you process_outgoing_events process? Alternatively, do you know if anyone who should have received the update saw any malformed requests?

**Comment by nigini** [comment]
You ARE right: This works beautifully...
```
2024-10-27 04:22:10.899 | INFO     | app.outgoing_activities:process_next_outgoing_activity:236 - 
payload={'@context':
(...)
'cc': ['https://blog.nigini.me/followers'], 
'published': '2024-10-06T04:22:33Z', 
'context': 'https://blog.nigini.me/contexts/92248b40d07342d195f03c510341f9b7', 
(...)
'published': '2024-10-06T04:22:33Z',
'updated': '2024-10-27T04:22:06Z', 
'type': 'Update', 
'signature': (...)
```
